---
- name: create docker working directory
  file:
    path: "{{docker.workingdir}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create dockerimage directory
  file:
    path: "{{docker_image.path}}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template dockerfile
  template:
    src: ./docker/Dockerfile
    dest: "{{docker_image.path}}/Dockerfile"
    owner: root
    group: root
    mode: 0554
  register: dockerfile

- name: copy dockerimage files
  copy:
    src: ./docker/
    dest: "{{docker_image.path}}"
    owner: root
    group: root
    mode: preserve
  register: dockerimage_files

- name: build image
  docker_image:
    path: "{{docker_image.path}}"
    name: "{{docker_image.name}}:{{docker_image.tag}}"
    force: "{{docker_image.force_build or dockerfile.changed or dockerimage_files.changed}}"
  register: dockerimage
